messages:
  land-create-name: "&2[ &f땅 &2] &7땅의 이름을 입력해 주세요."
  land-create-max-land: "&2[ &f땅 &2] &c최대 개수의 땅을 가지고 있어 구매할 수 없습니다."
  land-create-already-exists: "&2[ &f땅 &2] &c이미 해당 이름의 땅이 있습니다."
  land-create-other-land: "&2[ &f땅 &2] &c다른 땅과 겹칩니다."
  land-create-complete: "&2[ &f땅 &2] &a땅을 구매했습니다!"
  land-boarder: "&2[ &f땅 &2] &f경계선을 확인합니다."
  land-delete: "&2[ &f땅 &2] &e땅을 삭제했습니다. &6{1}원&e을 환불 받았습니다."
  teleport-home: "&2[ &f땅 &2] &e{1}&a땅으로 이동했습니다."
  land-coop-request: "&2[ &f땅 &2] &7공유할 플레이어의 이름 또는 UUID를 입력해 주세요."
  land-coop-max-player: "&2[ &f땅 &2] &c최대 공유 플레이어 수에 도달했습니다."
  land-coop-already-exists: "&2[ &f땅 &2] &c이미 해당 플레이어와 지역을 공유중입니다."
  land-coop-not-found-land: "&2[ &f땅 &2] &c찾을 수 없는 지역입니다. 관리자에게 문의하세요."
  land-coop-not-found: "&2[ &f땅 &2] &c해당 플레이어를 찾을 수 없습니다."
  land-coop-add: "&2[ &f땅 &2] &a해당 플레이어와 지역을 공유합니다."
  land-coop-remove: "&2[ &f땅 &2] &a더 이상 해당 플레이어와 지역을 공유하지 않습니다."
  land-no-world: "&2[ &f땅 &2] &c해당 월드에서는 구매할 수 없습니다."
  land-set-location: "&2[ &f땅 &2] &a현재 위치를 지역의 스폰 지점으로 설정했습니다."
  land-not-enough-money: "&2[ &f땅 &2] &c땅을 구매하기에 충분한 돈을 가지고 있지 않습니다!"
  land-no-name: "&2[ &f땅 &2] &c땅 이름으로 설정할 수 없는 문자가 포함되어 있습니다."
  land-dupe-name: "&2[ &f땅 &2] &6{1}&c이라는 땅은 이미 존재합니다."
maxLands: 4
findDistance: 100
worlds:
  - world