name: Lands
version: 1.0
main: org.mooner.lands.Lands
api-version: 1.18
authors: [ Mooner510 ]
description: Mooner's Land Plugin
depend:
  - NBTAPI
  - MoonerSethome
  - ShopChest-1.18
  - MoonerEco

commands:
  land:
    description: "land"
  rtp:
    aliases:
      - 렌덤텔포
      - fpsejaxpfvh